
########################################################
# cleaning Poaceae records from ALA for master data set
########################################################
# date created: 22/1
# last updated: 5/5/19 (Using Sue's v6 data & assigning native/endemic status)
          

# library --------------------------------------------------------
  library(tidyverse)
  library(data.table)
  
  rm(list = ls())
  
  setwd("C:/Users/s436862/Dropbox/Poaceae/Data files")

# -----------------------------------------------------------------------------------
# 1. APC native/exotic [naturlaised] tags -------------------------------------
  apc <- read.csv("ALA/Supplied data/nslsimplename-2015-06-25-2021.csv")
  glimpse(apc)
  
# include rank of species who have APC names
  dat <- filter(apc, rank == "Species" & classifications %in% c("[APC, APNI]", "[APNI, APC]"))
  
  a <- dat$apc_distribution
  b <- strsplit(as.character(a), split = ",")
  n_col <- unlist(lapply(b, function(x) length(x)))
  
  c <- matrix("", nrow = nrow(dat), ncol = max(n_col))
  for(i in 1:length(a)) if(n_col[i] > 0) c[i, 1:n_col[i]] <- b[[i]]
  
# trim leading and trailing white space
# function to trim leading and trailing white space
  trimm <- function( x ) {
    gsub("(^[[:space:]]+|[[:space:]]+$)", "", x)
  }  
  c <- apply(c, c(1,2), function(x) trimm(x))
  table(c)
  length(table(c))
  
  write.csv(table(c), "ALA/Generated data from cleaning steps/distribution fields beta.csv")
  
# notes ------------------------------------------------------------------------------
# I manually updated the list we just generated by individually tagging each unique 'feild'/ state tag as naturalised or native, in their own columns.
# -----------------------------------------------------------------------------------
# 2. create distribution (state) fields that ALA data can handle --------------------
# reload updated data file (see notes above for details)
  distr <- read.csv("ALA/Generated data from cleaning steps/Distribution fields updated.csv", header = T) %>%
           mutate(., native = ifelse(is.na(native) == T, 0, 1),
                  naturalised = ifelse(is.na(naturalised) == T, 0, 1))
  
  names(distr) <- c("id", "field", "native", "naturalised", "freq")  
  head(distr)
  
# create vectors to speed things up
  field <- distr$field
  naturalised <- distr$naturalised
  native <- distr$native
  
# identiy whether each species is listed as native or naturalised from the fields
  exo <- rowSums(apply(c, c(1, 2), function(x) naturalised[which(field == x)]))
  nat <- rowSums(apply(c, c(1, 2), function(x) native[which(field == x)]))
  
# now combine these to determine exclusively naturalised species (i.e. no native entry)
  exo_nat <- ifelse(nat == 0 & exo > 0, 1, 0) 
  
# number of naturalised species
  sum(exo_nat) # 2,952 exotics
  
# native species that have naturalised elsewhere in Australia
  native_nat <- ifelse(nat == 1 & exo > 0, 1, 0) 
  sum(native_nat) # 150 natives that have adventured outwards
  
# list each species as native/naturalised (0/1)
  dat.final <- mutate(dat, naturalised = exo_nat, native_naturalised = native_nat) %>%
    dplyr:::select(name, naturalised, native_naturalised, apc_name, apc_familia, familia, author, authority, genus, species) %>%
    arrange(familia, name) # so naturalised = exotic and native_naturalised = aventurous native; we assume all else are native
  
# output
  write.csv(dat.final, "ALA/Generated data from cleaning steps/APC names native & naturalised.csv")
  
# -------------------------------------------------------------------------------

# 3. clean ALA Poaceae data ---------------------------------------------------
# notes --------------------------------------------------------------------------
# removing: hybrids, records missing required column data (species name, lat, long, genus, year), [one] subspecies, and duplicate records
# ---------------------------------------------------------------------------------
# read in RDS file (note this was downloaded as CSV and I converted it to save space)
  ala.raw <- readRDS("ALA/Supplied data/records-2019-03-01.rds")
  
  
# required columns listed in header csv
  ala.header <- read.csv("ALA/Supplied data/records-2019-03-01 headings.csv", header = T) %>%
                dplyr::select(Required)
  ala.header <- as.vector(t(ala.header))
  ala.header.pos <- which(ala.header == "yes")
  
# select columns  
  ala <- ala.raw[, ..ala.header.pos]
  ala <- data.frame(ala)
  
# filter Na values
  ala2 <- ala %>% tidyr::drop_na("species", "genus", "decimalLatitude", "decimalLongitude", "year")
  
# filtering species: missing (blank) species, genera, 'forms', 'variety' and subspecies
  ala2a <- filter(ala2, grepl(" ", species))
  ala2b <- filter(ala2a, !grepl("form", taxonRank))
  ala2c <- filter(ala2b, !grepl("variety", taxonRank))
  ala2d <- filter(ala2c, !genus == "")

# remove incorrect year (where year = 0)
  table(ala2d$year, exclude = F)
  ala3 <- filter(ala2d, !year == "0")
  table(ala3$year, exclude = F)
 
# remove records' with coordiantes that are incorrect, uncertain (NA) and with large uncertainties (aove a threshold of 10 km radius)
  ala4 <- filter(ala3, coordinateUncertaintyInMeters <= 10000 & !coordinateUncertaintyInMeters <= 0)
  table(ala4$coordinateUncertaintyInMeters)
  
# remove duplicates 
# round lat/longs to ~1-km (2dp)
  ala4$decimalLatitude <- round(ala4$decimalLatitude, digits = 2)
  ala4$decimalLongitude <- round(ala4$decimalLongitude, digits = 2)
# find unique (distinct) records 
  ala5 <- ala4 %>% distinct(species, year, decimalLatitude, decimalLongitude, .keep_all = TRUE) 

# list of species
  spp.list <- levels(as.factor(ala5$species))
  length(spp.list)
  spp.list.df <- data.frame(spp.list) # 1445

  saveRDS(ala5, "ALA/Generated data from cleaning steps/ALA cleaned Poaceae.rds")
  
# -----------------------------------------------------------------------------------------
# 4. filter ALA spp. names with APC accepted names -----------------------------------------  
# ALA data thus far
  rm(list = ls())
  ala <- readRDS("ALA/Generated data from cleaning steps/ALA cleaned Poaceae.rds")
  
  ala$species[ala$species == "Neurachne alopecuroides"] <- "Neurachne alopecuroidea"
  table(ala$species == "Neurachne alopecuroidea")
  table(ala$species == "Neurachne alopecuroides")

# APC names
  apc <- read.csv("ALA/Generated data from cleaning steps/APC names native & naturalised.csv", strip.white = T) %>%
        dplyr::select(name, naturalised) 
  apc[apc$naturalised == "Neurachne alopecuroides"] <- "Neurachne alopecuroidea"
  
# ala species names
  ala$species <- as.factor(ala$species)
  ala.names <- data.frame(sci.name = as.character(levels(ala$species)), ala = 1) 
  
# apc species names and naturalised status
# first remove duplicate names
  apc.dup <- distinct(apc, name, .keep_all = T) # there were a ~170 duplicate names removed  
# 
  apc$name <- as.factor(apc$name) 
  apc.names <- data.frame(sci.name = as.character(levels(apc.dup$name)), 
                          apc = 1, 
                          native = table(apc.dup$name, apc.dup$naturalised)[, 1]) 
  
# match ALA and APC names and origins
  allnames <- merge(ala.names, apc.names, by = "sci.name", all = T)
  allnames <- mutate(allnames, ala = ifelse(is.na(ala) == T, 0, 1),
                     apc = ifelse(is.na(apc) == T, 0, 1),
                     tot = ala + apc) # so this is where they agree
  
# take only names which have both ALA and APC (i.e. tot = 2)  
  matching.names <- filter(allnames, tot == 2)
  
# subset ala based on these names
  ala$species <- as.character(ala$species)
  apc.names$sci.name <- as.character(apc.names$sci.name)
  ala.apc.names <- filter(ala, ala$species %in% matching.names$sci.name)
  
# add native status to ala data
  colnames(apc.names) <- c("species", "apc", "native")
  ala.status <- left_join(ala.apc.names, apc.names, by = "species")
  
  saveRDS(ala.status, "ALA/Generated data from cleaning steps/APC cleaned ALA Poaceae.rds")
  
# ----------------------------------------------------------------------------------------
# 5. doublecheck APC tags with Rachel/Randall's list ----------------------------
  rm(list = ls())
# read in cleaned renamed data 
  kh <- readRDS("ALA/Generated data from cleaning steps/APC cleaned ALA Poaceae.rds")
  Neurachne <- filter(kh, genus == "Neurachne")
# my species data
  kh.spp <- distinct(kh, species, .keep_all = T) %>%
    mutate(., native.kh = native) %>%
    dplyr::select(-native)
  
# Rachel/Randall's
  rg <- read.csv("ALA/Supplied data/Australia_plant_Census.csv", header = T)
  rg.spp <- distinct(rg, Taxon, .keep_all = T) %>%
    dplyr::select(., Taxon, native, nativeAndNaturalised, potentiallyNativeAndNaturalised) %>%
    mutate(., native.rg = ifelse(native == T, 1, 0)) %>%
    dplyr::select(-native)
  
# merge the two lists on common species 
  kh.spp$species <- as.character(kh.spp$species)
  rg.spp$Taxon <- as.character(rg.spp$Taxon)
  kh.rg.spp <- inner_join(kh.spp, rg.spp, by = c("species" = "Taxon"))

# mistmatched specie sbetween Randall's list and mine
# what are these?
  kh.rg.anti <- anti_join(kh.spp, rg.spp, by = c("species" = "Taxon")) 
  kh.rg.anti
# there few hybrids in there and poa caespitosa, which is misnamed
# I am not putting them back in
# if I were, I'd do this, however
  #kh.rg.spp.2 <- full_join(kh.rg.spp, kh.rg.anti) %>% mutate(., id = 1:nrow(.))
  
# check 1: Rachel's list has 'nativeAndNAturalised' tag, which I think are actually native for my purposes, I want to check if there are overlaps here
  kh.rg.spp.2 <- kh.rg.spp
  n.nat <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0) # 1 species (Aristida jerichoensis)
  n.nat2 <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.kh == 0) # 0. Cool.
# Aristida jerichoensis as native
  kh.rg.spp.2[kh.rg.spp.2$species == "Aristida jerichoensis", c("native.rg", "native.kh")] <- 1
# check
  j <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0) # beaut
# now on row "potentiallyNativeAndNAturalised"
  n.nat3 <- filter(kh.rg.spp.2, potentiallyNativeAndNaturalised == T & native.rg == 0) # 0 species fits this
  n.nat4 <- filter(kh.rg.spp.2, potentiallyNativeAndNaturalised == T & native.kh == 0) # 0 of mine do. Cool.
# check
  k <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0)
  
# check 2: where I have put native and Rachel has put exotic, I want to take Rachel's value; where I have put exotic and Rachel native, I will have a look
# first, kh = exotic, rg = native
  nat.exo <- filter(kh.rg.spp.2, native.kh == 0 & native.rg == 1) # Cenchrus purpurascens is native
  kh.rg.spp.2[kh.rg.spp.2$species == "Cenchrus purpurascens", "native.kh"] <- 1
# second, kh = native, rg = exotic
  exo.nat <- filter(kh.rg.spp.2, native.kh == 1 & native.rg == 0)
# update native.kh
  exo.nat$native.kh <- 0
# update spp. list
  kh.rg.spp.2[match(exo.nat$species, kh.rg.spp.2$species), ] <- exo.nat 

# manually checked with a changed spp. (Aristida behriana) and it is now an exotic
  l <- kh.rg.spp.2[kh.rg.spp.2$species == "Aristida behriana", "native.kh"] # = 0 :) 
  
# update native status
  spp.list <- kh.rg.spp.2 %>%
    mutate(., native = native.kh) %>%
    dplyr::select(species, native)
  
# correct column names/remove ones not needed
  kh3 <- kh.rg.spp.2 %>% dplyr::select(-native.rg, -apc) %>%
          mutate(status = ifelse(native.kh == 1, "native", "exotic")) %>%
          dplyr::select(species, status, -native.kh)
  spp.list$species <- as.character(spp.list$species)
 
# add native status tag to data
  kh.7 <- dplyr::select(kh, -native, -apc)
  kh8 <- left_join(kh.7, kh3, by = "species")
  glimpse(kh8)
  
# final check
  table(kh8$status, exclude = F)
  kh8a <- kh8 %>% tidyr::drop_na("status")

# save 
  saveRDS(kh8a, "ALA/Generated data from cleaning steps/APC and Randall cleaned ALA Poaceae.rds")

# 6. Add Pp, tribes and endemism, from Sue's data ------------------------------------
# notes -----------------------------------------------------------------
# Sue gave me an updated list of the grass data from above. 
# I'll update via species, as the record# will be different
# also updating tribes (sub.family), photosynthetic pathway, and native/endemic status
# -----------------------------------------------------------------------
# ALA data
  rm(list = ls())
  
# the ala data thus far
  ala <- readRDS("ALA/Generated data from cleaning steps/APC and Randall cleaned ALA Poaceae.rds") %>%
          dplyr::select(species, genus, year, decimalLatitude, decimalLongitude, status, recordID, recordedBy)
  colnames(ala) <- c("species", "genus", "year", "latitude", "longitude", "status", "recordID", "recorder")

  ala.spp <- distinct(ala, species, .keep_all = T) %>%
              dplyr::select(-latitude, -longitude, -recordID, -recorder)
  
# Sue's pp and tribe data
  sb.spp <- read.csv("Sue/6.AVH_grass-SB-endemics for KH.csv")
  colnames(sb.spp) <- c("species", "genus", "pp", "sub.family", "endemic")
  table(sb.spp$endemic)
  
# let's separate out between endemic species and just native  
  sb.spp2 <- mutate(sb.spp, status.sb = ifelse(endemic == "introduced", "exotic", "native"))
  table(sb.spp2$status.sb)
  
# step 1: checking if my species are native with respect to Sue's list ------------------------------------------    
# merge spp. lists (we are ignoring ones in Sue's list that are not in my one)
  full.spp <- left_join(ala.spp, sb.spp2, by = c("species", "genus"))
  head(full.spp)
  
# which statuses don't match?
  m <- filter(full.spp, status.sb == "exotic" & status == "native")    
  n <- filter(full.spp, status.sb == "native" & status == "exotic") # only 1: Eriochloa pseudoacrotricha
  
  full.spp[full.spp$species == "Eriochloa pseudoacrotricha", 4] <- "native" # update spp list
  ala[ala$species == "Eriochloa pseudoacrotricha", 7] <- "native" # update master list
# --------------------------------------------------------------------------------------------------------------
# save
  saveRDS(ala, "ALA/Generated data from cleaning steps/APC Randall Sue cleaned ALA Poaceae.rds")
  
# -----------------------------------------------------------

  
# photosynthetic pathway & tribe allocation -----------------
# notes ------------------------------------------------------
# each species needs a photosynthetic pathway (C3/C4)
# I will use Sue's recommendation of Watson (http://www.delta-intkey.com/)
# and Osborne et al. 2014, to assign genera that are missing.
# ------------------------------------------------------------
# data --------------------------------------------------------  
# ala thus far
  rm(list = ls())
  ala <- readRDS("ALA/Generated data from cleaning steps/APC Randall Sue cleaned ALA Poaceae.rds")
  ala.gen <- distinct(ala, genus)
  ala.spp <- distinct(ala, species)
  
# Sue's pp data
  sb.spp <- read.csv("Sue/6.AVH_grass-SB-endemics for KH.csv")
  colnames(sb.spp) <- c("species", "genus", "pp", "sub.family", "endemic")
  sb <- distinct(sb.spp, genus, .keep_all = T) %>%
    dplyr::select(genus, pp, sub.family)
  colnames(sb) <- c("genus", "w.pp", "sub.family")
  
# Osborne's pp data   
  os <- read.csv("Osborne C3-C4/c3-c4.csv", header = T)
  colnames(os) <- c("o.pp", "genus")
  table(os$o.pp) # note there are 'C3 and C4's and 'unknown' categories
  
# panicum spp. data
  panicum <- read.csv("Osborne C3-C4/Panicum.csv", header = T) %>%
    dplyr::select(ï..Species, Pathway)
  colnames(panicum) <- c("species", "pani.pp")
  head(panicum)
  
# assess coverage of pp from both sources ---------------------
# merge
  genera <- left_join(ala.gen, os, by = "genus") %>%
    left_join(., sb, by = "genus")
  head(genera) 
  table(genera$pp, exclude = F)
  table(genera$sub.family, exclude = F)
  
# do they disagree on any pp's?
  table(genera$o.pp, genera$w.pp, exclude = F) # only Panicum is disbuted, which is fine (see below)
  
  genera.c3 <- mutate(genera, final.pp = ifelse(w.pp == "C3"| o.pp == "C3", 1, 0)) %>%
    filter(., final.pp == 1) %>%
    mutate(final.pp = "C3")
  
  genera.c4 <- mutate(genera, final.pp = ifelse(w.pp == "C4"| o.pp == "C4", 1, 0)) %>%
    filter(., final.pp == 1) %>%
    mutate(final.pp = "C4")
  
  genera2 <- rbind(genera.c3, genera.c4)
  
# put back in genera which neither had (and were therefore excluded)
  genera3 <- left_join(genera, genera2)
# there is an extra row now (238 vs 237), and it's not unique within genera3 nor different to genera (??)
  
# manually updating genera with no pp --------------------------  
# notes --------------------------------------------------------
# these are not represented within Sue's Watson list or Osborne
# and will be taken from Watson's site: https://www.delta-intkey.com/
# --------------------------------------------------------------  
  ala2 <- ala
  
  gen3 <- genera3 %>% mutate(., pp = final.pp) %>%
    dplyr::select(genus, pp, sub.family)
# Lophopyrum
  gen3[gen3$genus == "Lophopyrum", "pp"] <- "C3"
  gen3[gen3$genus == "Lophopyrum", "sub.family"] <- "C3"
  
# Thinopyrum
  gen3[gen3$genus == "Thinopyrum", "pp"] <- "C3"
  gen3[gen3$genus == "Thinopyrum", "sub.family"] <- "C3"
  
# Avellinia
  gen3[gen3$genus == "Avellinia", "pp"] <- "C3"
  gen3[gen3$genus == "Avellinia", "sub.family"] <- "C3"
  
# Megathyrsus (synonym for Panicum maximum)
  gen3 <- filter(gen3, genus != "Megathyrsus")
  ala2[ala2$genus == "Megathyrsus", "genus"] <- "Panicum"
  ala2[ala2$species == "Megathyrsus maximus", "species"] <- "Panicum maximum"
  
# Molineriella (synonym for Periballia)
  gen3[gen3$genus == "Molineriella", "genus"] <- "Periballia"
  gen3[gen3$genus == "Periballia", "sub.family"] <- "C3"
  gen3[gen3$genus == "Periballia", "pp"] <- "C3"
  
  ala2[ala2$genus == "Molineriella", "genus"] <- "Periballia"
  ala2[ala2$species == "Molineriella minuta", "species"] <- "Periballia minuta"
  
# Elytrigia  
  gen3[gen3$genus == "Elytrigia", "pp"] <- "C3"
  gen3[gen3$genus == "Elytrigia", "sub.family"] <- "C3"
  
# Amelichloa (synonym for Nassella, but still recognised spp.)
  gen3[gen3$genus == "Amelichloa", "pp"] <- "C3"
  gen3[gen3$genus == "Amelichloa", "sub.family"] <- "C3"
  
# Steinchisma  
  gen3[gen3$genus == "Steinchisma", "pp"] <- "intermediate"
  gen3[gen3$genus == "Steinchisma", "sub.family"] <- "Paniceae"
  
# Moorochloa
  gen3[gen3$genus == "Moorochloa", "pp"] <- "C4"
  gen3[gen3$genus == "Moorochloa", "sub.family"] <- "Paniceae"
  
# Zuloagaea
  gen3[gen3$genus == "Zuloagaea", "pp"] <- "C4"
  gen3[gen3$genus == "Zuloagaea", "sub.family"] <- "Paniceae" 
  
# Jarava
  gen3[gen3$genus == "Jarava", "pp"] <- "C3"
  gen3[gen3$genus == "Jarava", "sub.family"] <- "C3" 
  
# update leftover tribes ----------------------------------
# where C3 --> C3,
# and we'll look up C4s on Watson's site
  gen3[gen3$pp == "C3", "sub.family"] <- "C3"
  table(gen3$sub.family, exclude = F)
  
# Triodia
  gen3[gen3$genus == "Triodia", "sub.family"] <- "Chloridoideae"  
  
# Cynodon
  gen3[gen3$genus == "Cynodon", "sub.family"] <- "Chloridoideae" 
  
# Andropogon
  gen3[gen3$genus == "Andropogon", "sub.family"] <- "Andropogoneae"
  
# Tragus  
  gen3[gen3$genus == "Tragus", "sub.family"] <- "Chloridoideae"
  
# Eleusine  
  gen3[gen3$genus == "Eleusine", "sub.family"] <- "Chloridoideae"  
  
# Axonopus
  gen3[gen3$genus == "Axonopus", "sub.family"] <- "Paniceae" 
  
# Melinis
  gen3[gen3$genus == "Melinis", "sub.family"] <- "Paniceae"
  
# Spartina
  gen3[gen3$genus == "Spartina", "sub.family"] <- "Chloridoideae"  
  
# Desmostachya  
  gen3[gen3$genus == "Desmostachya", "sub.family"] <- "Chloridoideae" 
  
# Eustachys
  gen3[gen3$genus == "Eustachys", "sub.family"] <- "Chloridoideae"   
  
# Saccharum 
  gen3[gen3$genus == "Saccharum", "sub.family"] <- "Andropogoneae" 
  
# Dinebra
  gen3[gen3$genus == "Dinebra", "sub.family"] <- "Chloridoideae"   
  
# Zea
  gen3[gen3$genus == "Zea", "sub.family"] <- "Andropogoneae"    
  
# Miscanthus
  gen3[gen3$genus == "Miscanthus", "sub.family"] <- "Andropogoneae" 
  
# Schmidtia
  gen3[gen3$genus == "Schmidtia", "sub.family"] <- "Chloridoideae"  
  
# Microstegium
  gen3[gen3$genus == "Microstegium", "sub.family"] <- "Andropogoneae" 
  
# Polytrias
  gen3[gen3$genus == "Polytrias", "sub.family"] <- "Andropogoneae"  
  
# Sorghastrum 
  gen3[gen3$genus == "Sorghastrum", "sub.family"] <- "Andropogoneae"    
  
# Crypsis
  gen3[gen3$genus == "Crypsis", "sub.family"] <- "Chloridoideae"  
  
  
# update ala ----------------------------------------------
  ala.g <- left_join(ala2, gen3, by = "genus")
  table(ala.g$status)
  table(ala.g$pp)
  
# updating Panicum, by species, from Osborne --------------
  ala.pan <- filter(ala.g, genus == "Panicum") %>%
    dplyr::select(species, genus) %>%
    distinct(species, .keep_all = T)
  head(ala.pan)
  
  ala.pan.pp <- left_join(ala.pan, panicum, by = "species")
  head(ala.pan.pp)
  
  ala.pan.pp$pani.pp[is.na(ala.pan.pp$pani.pp)] <- "C4"
  head(ala.pan.pp)
  pan <- ala.pan.pp
  colnames(pan) <- c("species", "genus", "pp")
  
# insert back into ala (this is tricky)
# isolate Panicum and remove 'wrong' pp
  ala.p <- filter(ala.g, genus == "Panicum") %>%
    dplyr::select(-pp)
  
# join with updated list
  ala.p2 <- left_join(ala.p, pan, by = c("genus", "species"))  
  table(ala.p2$pp)
  
# append
  ala.no.p <- filter(ala.g, genus != "Panicum")
  ala.append <- rbind(ala.p2, ala.no.p) %>%
                group_by(species) %>%
                arrange(species) %>%
                droplevels() %>%
                dplyr::select(species, genus, pp, status, year, sub.family, latitude, longitude, recordID, recorder)
  
# removing intermediate pp pathway
  ala.sorted <- filter(ala.append, pp != "intermediate") %>%
                droplevels()
  
# checks 
  table(ala.sorted$pp, ala.sorted$genus == "Panicum", exclude = F)
  table(ala.sorted$pp, exclude = F)
  table(ala.sorted$genus == "Neurachne", exclude = F)
  
# save
  saveRDS(ala.sorted, "ALA/Generated data from cleaning steps/APC Randall Sue Kyle cleaned ALA Poaceae.rds")

# ------------------------------------------------------------------  
  
# 7. Kyle's Poaceae chapter master data ----------------------------
# remove records who're outside of continental Australia
# raster template
  rm(list = ls())
  raster <- raster("Australia/aus 100 km v2.grd")

# which cells I want to keep
  cell.id <-  read.csv("C:/Users/s436862/Dropbox/Poaceae/Results/EVs/CSV/100 km EFs scaled.csv", header = T) %>%
    mutate(cell = cell.id) %>%
    dplyr::select(cell.category.v2, cell)
  
# spp records  
  dat <- readRDS("ALA/Generated data from cleaning steps/APC Randall Sue Kyle cleaned ALA Poaceae.rds") 
  
# remove cells which don't have a 'land' cell category via cell.id ----
# extract records by cell
  xy <- cbind(dat$longitude, dat$latitude)
  dat$cell <- raster::extract(raster, xy)

# attach cell.id and filter  
  dat.a <- left_join(dat, cell.id)
  dat.b <- filter(dat.a, cell.category.v2 == "land")
  
# plot check
  xy.b <- cbind(dat.b$longitude, dat.b$latitude)
  dat.br <- rasterize(xy.b, raster, fun = function(x,...) {length(unique(na.omit(x))) })
  plot(dat.br)
  plot(raster)

# checks
  table(dat.b$pp, exclude = F)
  table(dat.b$sub.family, exclude = F)
  table(dat.b$status, exclude = F)
  # all good
  dat.c <- distinct(dat.b, genus, sub.family)
  table(dat.c$genus, exclude = F)
  table(dat.c$species, exclude = F)
  # all good
  
# 7. save master copy data ---------------------------------------------  
  saveRDS(dat.b, "ALA/ALA master data/master grass data.rds")

# ----------------------------------------------------------------------------------

