
########################################################
# cleaning Poaceae records from ALA for master data set
########################################################
# notes -----------------------------------------------
# includes exotics (NZ records)
# -----------------------------------------------------
#######################################################
# date created: 22/1
# last updated: 4/3 (added in duplicate record removal)
#               8/3 (added ALA data and checked with Sue/AVH previous data)

# library --------------------------------------------------------
  library(dplyr)
  library(tidyr)
  library(data.table)
  
  rm(list = ls())
  
  setwd("C:/Users/s436862/Dropbox/Rarefaction/Data files")

# -----------------------------------------------------------------------------------
# 1. APC native/exotic [naturlaised] tags -------------------------------------
  apc <- read.csv("ALA/Supplied data/nslsimplename-2015-06-25-2021.csv")
  glimpse(apc)
  
# include rank of species who have APC names
  dat <- filter(apc, rank == "Species" & classifications %in% c("[APC, APNI]", "[APNI, APC]"))
  
  a <- dat$apc_distribution
  b <- strsplit(as.character(a), split = ",")
  n_col <- unlist(lapply(b, function(x) length(x)))
  
  c <- matrix("", nrow = nrow(dat), ncol = max(n_col))
  for(i in 1:length(a)) if(n_col[i] > 0) c[i, 1:n_col[i]] <- b[[i]]
  
# trim leading and trailing white space
  c <- apply(c, 2, function(x) trim(x))
  table(c)
  
  write.csv(table(c), "ALA/Generated data from cleaning steps/distribution fields beta.csv")
  
# notes ------------------------------------------------------------------------------
# I manually updated the list we just generated by individually tagging each unique 'feild'/ state tag as naturalised or native, in their own columns.
# I excluded tags based on if they were: ambiguous, thought to be extinct, two offshore islands (Lord Howe [LH] and MAcquarie [MI], leaving the other islands ot be removed later via their location-tags).
# -----------------------------------------------------------------------------------
  
# 2. create distribution (state) fields that ALA data can handle --------------------
# reload updated data file (see notes above for details)
  distr <- read.csv("ALA/Generated data from cleaning steps/Distribution fields updated.csv", header = T)
  distr <- mutate(distr, native = ifelse(is.na(native) == T, 0, 1),
                  naturalised = ifelse(is.na(naturalised) == T, 0, 1))
  
  names(distr) <- c("id", "field", "native", "naturalised", "freq")  
  
  exo <- matrix(0, nrow = nrow(c), ncol = ncol(c))
  nat <- matrix(0, nrow = nrow(c), ncol = ncol(c))
  
# create vectors to speed things up
  field <- distr$field
  naturalised <- distr$naturalised
  native <- distr$native
  
# identiy whether each species is listed as native or naturalised from the fields
  exo <- rowSums(apply(c, c(1, 2), function(x) naturalised[which(field == x)]))
  nat <- rowSums(apply(c, c(1, 2), function(x) native[which(field == x)]))
  
# now combine these to determine exclusively naturalised species (i.e. no native entry)
  exc_nat <- ifelse(nat == 0 & exo > 0, 1, 0) 
  
# number of naturalised species
  sum(exc_nat) # 2,952 exotics
  
# native species that have naturalised elsewhere in Australia
  native_nat <- ifelse(nat == 1 & exo > 0, 1, 0) 
  sum(native_nat) # 150 natives that have adventured outwards
  
# list each species as native/naturalised (0/1)
  dat.final <- mutate(dat, naturalised = exc_nat, native_naturalised = native_nat) %>%
    dplyr:::select(name, naturalised, native_naturalised, apc_name, apc_familia, familia, author, authority, genus, species) %>%
    arrange(familia, name) # so naturalised = exotic and native_naturalised = aventurous native; we assume all else are native
  
# output
  write.csv(dat.final, "ALA/Generated data from cleaning steps/APC names native & naturalised.csv")
  
# -------------------------------------------------------------------------------

# 3. clean ALA Poaceae data ---------------------------------------------------
# notes --------------------------------------------------------------------------
# removing: hybrids, records missing required column data (species name, lat, long, genus, year), [one] subspecies, and duplicate records
# ---------------------------------------------------------------------------------
# read in RDS file (note this was downloaded as CSV and I converted it to save space)
  ala.raw <- readRDS("ALA/Supplied data/records-2019-03-01.rds")
  
# required columns listed in header csv
  ala.header <- read.csv("ALA/Supplied data/records-2019-03-01 headings.csv", header = T) %>%
                dplyr::select(Required)
  ala.header <- as.vector(t(ala.header))
  ala.header.pos <- which(ala.header == "yes")
  
# select columns  
  ala <- ala.raw[, ..ala.header.pos]
  ala <- data.frame(ala)
  
# filter missing values
  ala2 <- ala %>% tidyr::drop_na("species", "genus", "decimalLatitude", "decimalLongitude", "year")
  
# filtering species: missing (blank) species, 'forms', 'variety' and subspecies
  ala2a <- filter(ala2, grepl(" ", species))
  ala2b <- filter(ala2a, !grepl("form", taxonRank))
  ala2c <- filter(ala2b, !grepl("variety", taxonRank))
  ala2d <- filter(ala2c, !grepl("subsp. ", species))

# remove incorrect year (where year = 0)
  table(ala2d$year, exclude = F)
  ala3 <- filter(ala2d, !year == "0")
  table(ala3$year, exclude = F)
 
# remove records' with coordiantes that are incorrect, uncertain (NA) and with large uncertainties (aove a threshold of 10 km radius) 
  ala4 <- filter(ala3, coordinateUncertaintyInMeters <= 10000 & !coordinateUncertaintyInMeters <= 0)
  table(ala4$coordinateUncertaintyInMeters)
  
# remove duplicates 
# round lat/longs to ~1-km (2dp)
  ala4$decimalLatitude <- round(ala4$decimalLatitude, digits = 2)
  ala4$decimalLongitude <- round(ala4$decimalLongitude, digits = 2)
# find unique (distinct) records 
  ala5 <- ala4 %>% distinct(species, year, decimalLatitude, decimalLongitude, .keep_all = TRUE) 
# removes a boatload of records

# list of species
  spp.list <- levels(as.factor(ala5$species))
  length(spp.list)
  spp.list.df <- data.frame(spp.list) # 1445

  saveRDS(ala5, "ALA/Generated data from cleaning steps/ALA cleaned Poaceae.rds")
  
# -----------------------------------------------------------------------------------------
# 4. filter ALA spp. names with APC accepted names -----------------------------------------  
# ALA data thus far
  rm(list = ls())
  ala <- readRDS("ALA/Generated data from cleaning steps/ALA cleaned Poaceae.rds")
  
# APC names
  apc <- read.csv("ALA/Generated data from cleaning steps/APC names native & naturalised.csv", strip.white = T) %>%
        dplyr::select(name, naturalised)
  
# ala species names
  ala$species <- as.factor(ala$species)
  ala.names <- data.frame(sci.name = as.character(levels(ala$species)), ala = 1) 
  
# apc species names and naturalised status
# first remove duplicate names
  apc.dup <- distinct(apc, name, .keep_all = T) # there were a ~170 duplicate names removed  
# 
  apc$name <- as.factor(apc$name) 
  apc.names <- data.frame(sci.name = as.character(levels(apc.dup$name)), 
                          apc = 1, 
                          native = table(apc.dup$name, apc.dup$naturalised)[, 1]) # this asks, "are you exotic? No? Ok, now you're native."
                          
# match ALA and APC names and origins
  allnames <- merge(ala.names, apc.names, by = "sci.name", all = T)
  allnames <- mutate(allnames, ala = ifelse(is.na(ala) == T, 0, 1),
                     apc = ifelse(is.na(apc) == T, 0, 1),
                     tot = ala + apc) # so this is where they agree
  
# take only names which have both ALA and APC (i.e. tot = 2)  
  matching.names <- filter(allnames, tot == 2)
  
# subset ala based on these names
  ala$species <- as.character(ala$species)
  apc.names$sci.name <- as.character(apc.names$sci.name)
  ala.apc.names <- filter(ala, ala$species %in% matching.names$sci.name)
  
# add native status to ala data
  colnames(apc.names) <- c("species", "apc", "native")
  ala.status <- left_join(ala.apc.names, apc.names, by = "species")
  
  saveRDS(ala.status, "ALA/Generated data from cleaning steps/APC cleaned ALA Poaceae.rds")
  
# ----------------------------------------------------------------------------------------
# 5. doublecheck APC tags with Rachel/Randall's list ----------------------------
  rm(list = ls())
# read in cleaned renamed data 
  kh <- readRDS("ALA/Generated data from cleaning steps/APC cleaned ALA Poaceae.rds")

# my species data
  kh.spp <- distinct(kh, species, .keep_all = T) %>%
    mutate(., native.kh = native) %>%
    dplyr::select(-native)
  
# Rachel/Randall's
  rg <- read.csv("ALA/Supplied data/Australia_plant_Census.csv", header = T)
  rg.spp <- distinct(rg, Taxon, .keep_all = T) %>%
    dplyr::select(., Taxon, native, nativeAndNaturalised, potentiallyNativeAndNaturalised) %>%
    mutate(., native.rg = ifelse(native == T, 1, 0)) %>%
    dplyr::select(-native)
  
# merge the two lists on common species 
  kh.spp$species <- as.character(kh.spp$species)
  rg.spp$Taxon <- as.character(rg.spp$Taxon)
  kh.rg.spp <- inner_join(kh.spp, rg.spp, by = c("species" = "Taxon"))
  
# we lost some species joining them -- what are these? Let's have a look
  kh.rg.anti <- anti_join(kh.spp, rg.spp, by = c("species" = "Taxon"))
  
# get the missing species back
  kh.rg.spp.2 <- full_join(kh.rg.spp, kh.rg.anti) %>% mutate(., id = 1:nrow(.))
  
# check: Rachel's list has 'nativeAndNAturalised' tag, which I think are actually native for my purposes, I want to check if there are overlaps here
  n.nat <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0) # 1 species (Aristida jerichoensis)
  n.nat2 <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.kh == 0) # 0. Cool.
  
# Aristida jerichoensis as native
  kh.rg.spp.2[kh.rg.spp.2$species == "Aristida jerichoensis", c("native.rg", "native.kh")] <- 1

# check
  j <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0) # beaut
  
# now on row "potentiallyNativeAndNAturalised"
  n.nat3 <- filter(kh.rg.spp.2, potentiallyNativeAndNaturalised == T & native.rg == 0) # 0 species fits this
  n.nat4 <- filter(kh.rg.spp.2, potentiallyNativeAndNaturalised == T & native.kh == 0) # 0 of mine do. Cool.
# check
  k <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0)
  
# second check: where I have put native and Rachel has put exotic, I want to take Rachel's value; where I have put exotic and Rachel native, I will have a look at the prevalance
# first, prevalance
  nat.exo <- filter(kh.rg.spp.2, native.kh == 0 & native.rg == 1) # Cenchrus purpurascens is native
  kh.rg.spp.2[kh.rg.spp.2$species == "Cenchrus purpurascens", "native.kh"] <- 1
  
# spp. which slipped thorugh net
  exo.nat <- filter(kh.rg.spp.2, native.kh == 1 & native.rg == 0)
  
# update native.kh
  exo.nat$native.kh <- 0
  
# update spp. list
  kh.rg.spp.2[match(exo.nat$species, kh.rg.spp.2$species), ] <- exo.nat 

# manually checked with a changed spp. (Aristida behriana) and it is now an exotic
  l <- kh.rg.spp.2[kh.rg.spp.2$species == "Aristida behriana", "native.kh"] # = 0 :) 
  
  spp.list <- kh.rg.spp.2 %>%
    mutate(., native = native.kh) %>%
    dplyr::select(species, native)
  
# correct column names/remove ones not needed
  kh3 <- kh.rg.spp.2 %>% dplyr::select(-native.rg, -apc, -id) %>%
          mutate(native = native.kh) %>%
          dplyr::select(species, native, -native.kh)
  spp.list$species <- as.character(spp.list$species)
 
# add native status tag to data
  kh.7 <- dplyr::select(kh, -native, -apc)
  kh8 <- left_join(kh.7, kh3, by = "species")

# save 
  saveRDS(kh8, "ALA/Generated data from cleaning steps/APC and Randall cleaned ALA Poaceae.rds")

# 6. Add Pp and tribes and compare to Sue's data ------------------------------------
# notes -----------------------------------------------------------------
# Sue gave me an updated list of the grass data from above. 
# I'll update via species, as the record# will be different
# also updating tribes (sub.family) and photosynthetic pathway -- can't hurt having these in the master data
# -----------------------------------------------------------------------
# ALA data
  rm(list = ls())
  ala <- readRDS("ALA/Generated data from cleaning steps/APC and Randall cleaned ALA Poaceae.rds") %>%
            dplyr::select(species, genus, year, decimalLatitude, decimalLongitude, native) %>%
            group_by(species)
  colnames(ala) <- c("species", "genus", "year", "latitude", "longitude", "status.kh") 

# Sue's data
  sb.grass <- read.csv("ALA/Supplied data/4.AVH grass - SB sorted into tribes.csv")
  sb.grass <- sb.grass[, 3:9] # not sure how to type the first column's name for select function
  sb.grass <- sb.grass %>% mutate(status.sb = status) %>%
              dplyr::select(-status)
  
# remove duplicates in Sue's data
# round lat/longs to ~1-km (2dp)
  sb.grass$latitude <- round(sb.grass$latitude, digits = 2)
  sb.grass$longitude <- round(sb.grass$longitude, digits = 2)
  
# unique (distinct) records 
  sb.grass2 <- sb.grass %>% distinct(species, year, latitude, longitude, .keep_all = TRUE)
  
# species and their statues
  ala.spp <- distinct(ala, species, .keep_all = T) %>%
              dplyr::select(species, status.kh)
  sb.spp <- distinct(sb.grass2, species, .keep_all = T) %>%
              dplyr::select(., species, status.sb)
  
# merge spp. lists
  full.spp <- full_join(ala.spp, sb.spp, by = "species")
  
  
# which spp don't match?
  sb.ala <- anti_join(sb.spp, ala.spp, by = "species") 
  ala.sb <- anti_join(ala.spp, sb.spp, by = "species") %>%
            arrange(species, desc(status.kh))
  
# changing species in ala data ---------------------------------------------------------
  ala2 <- ala
# Poa caespitosa's accepted name: Poa labillardierei (which exists already)
  ala2[ala2$species == "Poa caespitosa", 1] <- "Poa labillardierei"
# Agrostis canina --> Agrostis muelleriana
  ala2[ala2$species == "Agrostis canina", 1] <- "Agrostis muelleriana"
# Apera spica-venti --> remove
  ala2 <- filter(ala2, species != "Apera spica-venti")
# Cynochloris macivorii --> remove
  ala2 <- filter(ala2, species != "Cynochloris macivorii")
# Cynochloris reynoldensis --> remove
  ala2 <- filter(ala2, species != "Cynochloris reynoldensis")
# Cyrtococcum deltoideum --> exo
  ala2[ala2$species == "Cyrtococcum deltoideum", "status.kh"] <- 0
# Digitaria velutin --> remove
  ala2 <- filter(ala2, species != "Digitaria velutin")
# Eriochloa nubica -- > Eriochloa pseudoacrotricha
  ala2[ala2$species == "Eriochloa nubica", 1] <- "Eriochloa pseudoacrotricha"
# Festulolium loliaceum -- > remove
  ala2 <- filter(ala2, species != "Festulolium loliaceum")
# Lachnagrostis contracta -- > remove
  ala2 <- filter(ala2, species != "Lachnagrostis contracta")
# Melica uniflora --> remove
  ala2 <- filter(ala2, species != "Melica uniflora")
# Mibora minima --> remove
  ala2 <- filter(ala2, species != "Mibora minima")
# Milium effusum --> exo [nz native]
  ala2[ala2$species == "Milium effusum", "status.kh"] <- 0
# Oryza nivara -- > remove
  ala2 <- filter(ala2, species != "Oryza nivara")
# Poa arachnifera --> remove
  ala2 <- filter(ala2, species != "Poa arachnifera")
# Polypogon fugax --> exotic
  ala2[ala2$species == "Polypogon fugax", "status.kh"] <- 0
# Spinifex alterniflorus --> remove
  ala2 <- filter(ala2, species != "Spinifex alterniflorus")
# Thaumastochloa heteromorpha --> remove
  ala2 <- filter(ala2, species != "Thaumastochloa heteromorpha")
# Tripsacum dactyloides --> exotic
  ala2 <- filter(ala2, species != "Tripsacum dactyloides")
# Eriochloa pseudoacrotricha is somehow native for 1 row, all else exotic; lat/longs are weird so I am removing it
  ala2 <- ala2[!(ala2$species == "Eriochloa pseudoacrotricha" & ala2$status.kh == 1),] 
  
# -------------------------------------------------------------------------
# attahing photsynthetic pathway -------------------------------------------------
# (using  Sue's recommendations on source)
  sb <- read.csv("ALA/Supplied data/5. AVH grass - SB sorted into tribes.csv", header = T)
  table(sb$genus, sb$pp)
  # no genus has both C3 and C4 records
  
# genera lists
  poa <- ala2
  kh.genera <- data.frame(poa$genus)
  colnames(kh.genera) <- "genus"
  sb.genera <- data.frame(sb$genus)
  colnames(sb.genera) <- "genus"
# there are 5 genera that ALA have that AVH/Sue doesn't
  kh.gen <- anti_join(kh.genera, sb.genera, by = "genus")
  kh.gen.dis <- distinct(kh.gen)

# which Pp and tribe do these belong to? 
# Using the Watson database: http://www.delta-intkey.com/
# Anthosachne --> C3; tribe = C3 (none)
# Calamagrostis --> C3; "             "
# Desmostachya --> C4; but exotic; Chloridoideae (1)
# Milium --> C3 (exo)
# Schmidtia -- C4 (exo)
  
# pp time
  sb.pp <- distinct(sb, genus, .keep_all = T) %>%
    dplyr::select(genus, pp, sub.family)
  
  merged.gen <- left_join(kh.genera, sb.pp, by = "genus")
  
# update the five missing genera of pp and tribe
  merged.gen[merged.gen$genus == "Anthosachne", "pp"] <- 1 # c3 = 1
  merged.gen[merged.gen$genus == "Calamagrostis", "pp"] <- 1 
  merged.gen[merged.gen$genus == "Desmostachya", "pp"] <- 2 # c4 = 2 
  merged.gen[merged.gen$genus == "Desmostachya", "sub.family"] <- 1 # Chloridoideae = 1 
  merged.gen[merged.gen$genus == "Milium", "pp"] <- 1 
  merged.gen[merged.gen$genus == "Schmidtia", "pp"] <- 2 
  
  gen2 <- distinct(merged.gen)
  
# pp ----------------------------------------------------------------
# 1 = C3 and 2 = C4
  gen3 <- mutate(gen2, pp = ifelse(pp == 1, "C3", "C4"))
  
# tribes, pp ----------------------------------------------------------------
# notes -----------------------------------------------------------------
# oddly, there are many tribes missing tags from the supplied data from Sue
# I will tehrefore attach these manually, using Watson et al. as the source, as I did for the pp
# -----------------------------------------------------------------------
# C4 taxa with no tribe status corrected --------------------------------
  missing.tribes <- gen3[is.na(gen3$sub.family), "genus"] # 19 of them

# #1 Arundinella =  Panicoideae; Andropogonodae
  gen3[gen3$genus == "Arundinella", "sub.family"] <- "Andropogoneae" 
  
# #2 Rottboellia =  Panicoideae; Andropogonodae
  gen3[gen3$genus == "Rottboellia", "sub.family"] <- "Andropogoneae"   

# #3 Cynodon =  Chloridoideae
  gen3[gen3$genus == "Cynodon", "sub.family"] <- "Chloridoideae"   
  
# #4 Andropogon =  Panicoideae; Andropogonodae
  gen3[gen3$genus == "Andropogon", "sub.family"] <- "Andropogoneae"
  
# #5 Melinis =  Panicoideae; Paniceae
  gen3[gen3$genus == "Melinis", "sub.family"] <- "Paniceae"  
  
# #6 Spartina = Chloridoideae
  gen3[gen3$genus == "Spartina", "sub.family"] <- "Chloridoideae"  
  
# #7 Axonopus = Panicoideae; Paniceae
  gen3[gen3$genus == "Axonopus", "sub.family"] <- "Paniceae"  
  
# #8 Eleusine =  Chloridoideae
  gen3[gen3$genus == "Eleusine", "sub.family"] <- "Chloridoideae"  
  
# #9 Dinebra =  Chloridoideae
  gen3[gen3$genus == "Dinebra", "sub.family"] <- "Chloridoideae"  
  
# #10 Eustachys = Chloridoideae
  gen3[gen3$genus == "Eustachys", "sub.family"] <- "Chloridoideae"  
  
# #11 Miscanthus =  Panicoideae; Andropogonodae
  gen3[gen3$genus == "Miscanthus", "sub.family"] <- "Andropogoneae"    
  
# #12 Moorochloa =  Panicoideae; Paniceae
  gen3[gen3$genus == "Moorochloa", "sub.family"] <- "Paniceae" 
  
# #13 Schmidtia =  Chloridoideae
  gen3[gen3$genus == "Schmidtia", "sub.family"] <- "Chloridoideae"
  
# #14 Microstegium =  Panicoideae; Andropogoneae
  gen3[gen3$genus == "Microstegium", "sub.family"] <- "Andropogoneae"
  
# #15 Saccharum =  Panicoideae; Andropogoneae
  gen3[gen3$genus == "Saccharum", "sub.family"] <- "Andropogoneae"
  
# #16 Taeniatherum =  C3
  gen3[gen3$genus == "Taeniatherum", c("pp", "sub.family")] <- "C3"
  
# #17 Taeniatherum =  Panicoideae; Andropogoneae
  gen3[gen3$genus == "Taeniatherum", "sub.family"] <- "Andropogoneae"
  
# #18 Zuloagaea =  Panicoideae; Paniceae
  gen3[gen3$genus == "Zuloagaea", "sub.family"] <- "Paniceae"  
  
# #19 Sorghastrum =  Panicoideae; Andropogoneae
  gen3[gen3$genus == "Sorghastrum", "sub.family"] <- "Andropogoneae"  
  
# #20 Polytrias =  Panicoideae; Andropogoneae
  gen3[gen3$genus == "Polytrias", "sub.family"] <- "Andropogoneae"  
 
# #21 Crypsis =  Chloridoideae
  gen3[gen3$genus == "Crypsis", "sub.family"] <- "Chloridoideae"  
   
# ------------------------------------------------------------------------  
# C3 --> tribe "C3" 
  gen3[gen3$pp == "C3", "sub.family"] <- "C3"
  
# triodia --> Triodia [will be excluded for Sue's purposes]
  gen3[gen3$genus == "Triodia", "sub.family"] <- "Triodia"

# tribes: 1 = Chloridoideae
  gen3$sub.family[gen3$sub.family == 1] <- "Chloridoideae"

# tribes: 2 = Panicoideae, Paniceae
  gen3$sub.family[gen3$sub.family == 2] <- "Paniceae"  
  
# tribes: 3 = Panicoideae, Andropogoneae
  gen3$sub.family[gen3$sub.family == 3]  <- "Andropogoneae" 
  
# tribes: 4 = Micrairoideae
  gen3$sub.family[gen3$sub.family == 4] <- "Micrairoideae" 
  
# tribes: 5 = Aristidoideae
  gen3$sub.family[gen3$sub.family == 5] <- "Aristidoideae"   
  
# master data -------------------------------------------------------------------
# merge with actual species records
  poa2 <- left_join(poa, gen3, by = "genus")
  
# status: native and exotic
  poa3 <- mutate(poa2, status = ifelse(status.kh == 1, "native", "exotic")) %>%
    dplyr::select(-status.kh)
  
# checks
  poa4 <- distinct(poa3, genus, sub.family)
  table(poa3$genus, exclude = F)
  table(poa3$species, exclude = F)
  table(poa3$pp, exclude = F)
  table(poa3$sub.family, exclude = F)
  table(poa3$status, exclude = F)
  # all good
  
# 7. save grass as master copy data ---------------------------------------------  
  saveRDS(poa3, "ALA/2019 ALA master data/master grass data.rds")

# ----------------------------------------------------------------------------------

