

###############################################################
# Read in APC data and identify status (native/nturalised) tags
###############################################################

# date created: 22/1
# last updated: 4/3 (added in duplicate record removal)

# Library --------------------------------------------------------
  library(dplyr)
  
  rm(list = ls())
  
  setwd("C:/Users/s436862/Dropbox/Rarefaction/Data files")

# `1. oraganise native/exotic [naturlaised] tags based on State & fields -----------
# function to trim leading and trailing white space
  trim <- function( x ) {
    gsub("(^[[:space:]]+|[[:space:]]+$)", "", x)
  }  
  
  apc <- read.csv("AVH/Supplied data/nslsimplename-2015-06-25-2021.csv")
  glimpse(apc)
  
# include rank of species who have APC names
  dat <- filter(apc, rank == "Species" & classifications %in% c("[APC, APNI]", "[APNI, APC]"))
  
  a <- dat$apc_distribution
  b <- strsplit(as.character(a), split = ",")
  n_col <- unlist(lapply(b, function(x) length(x)))
  
  c <- matrix("", nrow = nrow(dat), ncol = max(n_col))
  for(i in 1:length(a)) if(n_col[i] > 0) c[i, 1:n_col[i]] <- b[[i]]
  
# trim leading and trailing white space
  c <- apply(c, 2, function(x) trim(x))
  table(c)
  
  write.csv(table(c), "AVH/Generated data from cleaning steps/distribution fields beta.csv")
  
# notes ------------------------------------------------------------------------------
# I manually updated the list we just generated by individually tagging each unique 'feild'/ state tag as naturalised or native, in their own columns.
# I excluded tags based on if they were: ambiguous, thought to be extinct, two offshore islands (Lord Howe [LH] and MAcquarie [MI], leaving the other islands ot be removed later via their location-tags).
# -----------------------------------------------------------------------------------
# 2. attach native/exotic [naturalised] tags to species in AVH data --------------------
# reload updated data file (see notes above for details)
  distr <- read.csv("AVH/Generated data from cleaning steps/Distribution fields updated.csv", header = T)
  distr <- mutate(distr, native = ifelse(is.na(native) == T, 0, 1),
                  naturalised = ifelse(is.na(naturalised) == T, 0, 1))
  
  names(distr) <- c("id", "field", "native", "naturalised", "freq")  
  
  exo <- matrix(0, nrow = nrow(c), ncol = ncol(c))
  nat <- matrix(0, nrow = nrow(c), ncol = ncol(c))
  
# create vectors to speed things up
  field <- distr$field
  naturalised <- distr$naturalised
  native <- distr$native
  
# identiy whether each species is listed as native or naturalised from the fields
  exo <- rowSums(apply(c, c(1, 2), function(x) naturalised[which(field == x)]))
  nat <- rowSums(apply(c, c(1, 2), function(x) native[which(field == x)]))
  
# now combine these to determine exclusively naturalised species (i.e. no native entry)
  exc_nat <- ifelse(nat == 0 & exo > 0, 1, 0) 
  
# number of naturalised species
  sum(exc_nat) # 2,952 exotics
  
# native species that have naturalised elsewhere in Australia
  native_nat <- ifelse(nat == 1 & exo > 0, 1, 0) 
  sum(native_nat) # 150 natives that have adventured outwards
  
# list each species as native/naturalised (0/1)
  dat.final <- mutate(dat, naturalised = exc_nat, native_naturalised = native_nat) %>%
    dplyr:::select(name, naturalised, native_naturalised, apc_name, apc_familia, familia, author, authority, genus, species) %>%
    arrange(familia, name) # so naturalised = exotic and native_naturalised = aventurous native; we assume all else are native
  
# output
  write.csv(dat.final, "AVH/Generated data from cleaning steps/APC names native & naturalised.csv")
  
# -------------------------------------------------------------------------------
# 3. doublecheck APC tags with Racyhel/Randall's list ----------------------------
# notes -----------------------------------------------------------------------
# this is in two parts: first, Richard's method using APC names
# second, verify this using Randall's list, donated by Rachel Gallagher
# ---------------------------------------------------------------------------------  
# part 1 -----------------------------------------------------------------------
  rm(list = ls())
  
# read in AVH data
  avh <- read.table("AVH/Supplied data/AVH data extracted.dat", sep="\t", header=T, strip.white = T)
  
# remove hybrids: denoted by " x " in names
  avh <- filter(avh, !grepl(" x ", Species...matched))
 
# list of species
  spp.list <- levels(avh$Species...matched)
  length(spp.list)
  
# read in APC names
  apc <- read.csv("AVH/Generated data from cleaning steps/APC names native & naturalised.csv", strip.white = T)
  
# remove hybrid(s)
  apc <- filter(apc, !grepl(" x ", name))
  
  apc.origin <- dplyr::select(apc, name, naturalised)
  
# compare and correct names
# create data frame of all avh species names
  avh$Species...matched <- as.factor(avh$Species...matched)
  avh.names <- data.frame(sci.name = as.character(levels(avh$Species...matched)), avh = 1) 
  
# do the same for the apc, but also denote native and naturalsied status
  apc.origin$name <- as.factor(apc.origin$name) 

# first, though: duplicate name check
  apc.origin.dup <- distinct(apc.origin, name, .keep_all = T) # there were a ~150 duplicate names removed

  apc.names <- data.frame(sci.name = as.character(levels(apc.origin.dup$name)), 
                          apc = 1, 
                          native = table(apc.origin.dup$name, apc.origin.dup$naturalised)[, 1]) 
                          # this says "are you exotic? No? Ok, you're now native."
                          
# matching names and origin
  allnames <- merge(avh.names, apc.names, by = "sci.name", all = T)
  allnames <- mutate(allnames, avh = ifelse(is.na(avh) == T, 0, 1),
                     apc = ifelse(is.na(apc) == T, 0, 1),
                     tot = avh + apc) # so this is where they agree
  
# take only names which have both AVH and APC (i.e. = 2)  
  matching.names <- filter(allnames, tot == 2)
  
# subset avh based on these names
  avh$Species...matched <- as.character(avh$Species...matched)
  apc.names$sci.name <- as.character(apc.names$sci.name)
  avh.apc.names <- filter(avh, avh$Species...matched %in% matching.names$sci.name)
  
# add native status to avh data
  colnames(apc.names) <- c("Species...matched", "apc", "native")
  avh.status <- left_join(avh.apc.names, apc.names, by = "Species...matched")

# part 2 --------------------------------------------------------------------------
# using Rachel/Randall for the rest of the naturalised status tagging
# Note: can remove everything from workspace that isn't avh.status
  rm(list=setdiff(ls(), "avh.status")) 

# my data
  kh <- avh.status
  kh.spp <- distinct(kh, Species...matched, .keep_all = T) %>%
    mutate(., native.kh = native) %>%
    dplyr::select(-native)
  
# Rachel/Randall's
  rg <- read.csv("AVH/Supplied data/Australia_plant_Census.csv", header = T)
  rg.spp <- distinct(rg, Taxon, .keep_all = T) %>%
    dplyr::select(., Taxon, native, nativeAndNaturalised, potentiallyNativeAndNaturalised) %>%
    mutate(., native.rg = ifelse(native == T, 1, 0)) %>%
    dplyr::select(-native)
  
# merge the two lists on common species 
  kh.spp$Species...matched <- as.character(kh.spp$Species...matched)
  rg.spp$Taxon <- as.character(rg.spp$Taxon)
  kh.rg.spp <- inner_join(kh.spp, rg.spp, by = c("Species...matched" = "Taxon"))
  
# we lost some species joining them -- what are these? Let's have a look
  kh.rg.anti <- anti_join(kh.spp, rg.spp, by = c("Species...matched" = "Taxon"))
  
# get the missing species back
  kh.rg.spp.2 <- full_join(kh.rg.spp, kh.rg.anti) %>% mutate(., id = 1:nrow(.))
  
# check: Rachel's list has 'nativeAndNAturalised' tag, which I think are actually native for my purposes, I want to check if there are overlaps here
  n.nat <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0) # 21 species fit this
  n.nat2 <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.kh == 0) # 0 of mine do. Cool.
  
# 21 exotics -> native; doing it manually because this is hurting my brain
  n.nat[,18] <- 1
  kh.rg.spp.2[c(203,  238,  420,  569,  633,  
                        722, 1068, 1231, 1462, 2696, 
                        2711, 2712, 3173, 3394, 3657, 
                        3986, 6119, 9340, 9513, 9716, 
                        9762), c(15, 18)] <- 1
# check
  j <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0)
  
# now on row "potentiallyNativeAndNAturalised"
  n.nat3 <- filter(kh.rg.spp.2, potentiallyNativeAndNaturalised == T & native.rg == 0) # 1 species fits this
  n.nat4 <- filter(kh.rg.spp.2, potentiallyNativeAndNaturalised == T & native.kh == 0) # 0 of mine do. Cool.
  
# 1 exoitc -> native  
  kh.rg.spp.2[5655, c(15, 18)] <- 1
# check
  k <- filter(kh.rg.spp.2, nativeAndNaturalised == T & native.rg == 0)
  
# Randall's check: where I have put native and Rachel has put exotic, I want to take Rachel's value; where I have put exotic and Rachel native, I will have a look at the prevalance
# prevalance
  nat.exo <- filter(kh.rg.spp.2, native.kh == 0 & native.rg == 1) # Cenchrus purpurascens is native
  kh.rg.spp.2[3059, 15] <- 1
  
# spp. which slipped thorugh net
  exo.nat <- filter(kh.rg.spp.2, native.kh == 1 & native.rg == 0)
  
# update native.kh
  exo.nat$native.kh <- 0
  
# update spp. list
  kh.rg.spp.2[match(exo.nat$Species...matched, kh.rg.spp.2$Species...matched), ] <- exo.nat # manually checked with a changed spp. (Aristida behriana) and it is now an exotic
  spp.list <- kh.rg.spp.2 %>%
    mutate(., native = native.kh) %>%
    dplyr::select(Species...matched, native)
  
# update avh list
  kh2 <- kh %>% dplyr::select(-native, -apc)
  spp.list$Species...matched <- as.character(spp.list$Species...matched)
  kh2$Species...matched <- as.character(kh2$Species...matched)
  kh3 <- left_join(kh2, spp.list, by = "Species...matched")
  
# 4. remove duplicates -------------------------------------------------------
# round lat/longs to ~1-km (2dp)
  kh3$Latitude...processed <- round(kh3$Latitude...processed, digits = 2)
  kh3$Longitude...processed <- round(kh3$Longitude...processed, digits = 2)
  
# find unique (distinct) records 
  kh4 <- kh3 %>% distinct(Species...matched, Year...parsed, Latitude...processed, Longitude...processed, .keep_all = TRUE)
  
  # find duplicate records
  #dat.dupl <- anti_join(dat, dat.dist, by = "id")  
  
# 5. save master AVH data copy ----------------------------------------------------
  write.csv(kh4, "AVH/2019 master data/AVH master data.csv", row.names = F)
  
# as well as grass data 
  avh <- read.csv("AVH/2019 master data/AVH master data.csv")
  avh.grass <- filter(avh, Family...matched == "Poaceae")

  colnames(avh.grass) <- c("scientific.name",
                           "matched.scientific.name",
                           "order",
                           "family",
                           "genus",
                           "species",
                           "latitude",
                           "longitude",
                           "IBRA.region",
                           "state",
                           "year",
                           "taxon.identification.issue",
                           "inferred.duplicate.Record",
                           "name.not.in.national.checklists",
                           "status")
  avh.grass <- dplyr::select(avh.grass, scientific.name, species, genus, latitude, longitude, year, status)

  write.csv(avh.grass, "AVH/Generated data from cleaning steps/AVH grass.csv", row.names = F)
  
# 6. save master grass data copy ------------------------------------
# notes -----------------------------------------------------------------
# Sue gave me an updated list of the grass data from above. 
# I have since updated it by removing duplicates.
# Therefore, I will upload hers and do the duplicate thing now (as this should be the only difference).
# However, ideally, I'd have done that previously.
# However, this should give the same results (i.e. length(Sue.data) == length(my.data)), which I'll check here
# -----------------------------------------------------------------------
# data
  kh.grass <- read.csv("AVH/Generated data from cleaning steps/AVH grass.csv", header = T) %>%
              select(-scientific.name)
  sb.grass <- read.csv("AVH/Supplied data/4.AVH grass - SB sorted into tribes.csv")
  sb.grass <- sb.grass[, 3:9] # not sure how to type the first column's name for select function
  
# remove duplicates in Sue's data
# round lat/longs to ~1-km (2dp)
   sb.grass$latitude <- round(sb.grass$latitude, digits = 2)
   sb.grass$longitude <- round(sb.grass$longitude, digits = 2)
  
# unique (distinct) records 
   sb.grass2 <- sb.grass %>% distinct(species, year, latitude, longitude, .keep_all = TRUE)
  
# there is 1 row diffience in the lengths of the data frames -- let's see what it is
  dup <- anti_join(sb.grass2, kh.grass, by = c("species", "genus", "latitude", "longitude", "year")) # 72 distinct rows? But there's only 1 row length difference.
         # executive decision: it doesn't matter; using Sue's data from now on.
  
# save grass as master copy data
  write.csv(sb.grass2, "AVH/2019 master data/master grass data.csv", row.names = F)

# ----------------------------------------------------------------------------------






  